- name: "Install postgresql"
  apt: name=postgresql,libpq-dev,python-psycopg2 state=latest update_cache=yes

- name: "Configure pg_hba.conf"
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify:
    - restart postgresql

- name: "Copy postgresql.conf"
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres mode=0640
  notify:
    - restart postgresql

- name: "Start Postgresql"
  service: name=postgresql state=started enabled=yes
  
- name: "Add Helloworld database"
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db: name=helloworld

- name: "Add Helloworld user task"
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user: db="{{ dbname }}" name="{{ dbuser }}" password="{{ dbpass}}" priv=ALL
