- name: "Install vim"
  apt: name=vim state=latest

- name: "Use best mirrors"
  apt_repository:
    repo: "deb http://eu.archive.ubuntu.com/ubuntu/ {{ item }}"
  with_items:
  - trusty main restricted
  - trusty universe
  - trusty-updates main restricted
  - trusty-security main
  - trusty-security universe
