- name: "Add Java8 repo"
  apt_repository: repo=ppa:webupd8team/java

- name: "Accept Oracle license"
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: "Install Java 8 Oracle"
  apt: name=oracle-java8-installer state=latest

- name: "Install Git"
  apt: name=git state=latest

- name: "Install application user"
  user: name=appuser system=yes

- name: "Clone repo"
  git: repo=https://github.com/pal-thomassen/trh-linux-kurs.git
       dest=/home/appuser/trh-linux-kurs

- name: "Build app"
  shell: ./gradlew build oneJar
  args:
    chdir: /home/appuser/trh-linux-kurs/app/

- name: "Install configuration"
  template: src=app.yml.j2 dest=/home/appuser/app.yml mode=0644

- name: "Install upstart script"
  copy: src=helloworld.conf dest=/etc/init/helloworld.conf

- name: "Start Hello World Application"
  service: name=helloworld state=started enabled=yes
